### ISSUE TITLE
Set a reasonable generation speed

### ISSUE THREAD

**Issue by VillagerGold** [SirSquidly/Oceanic-Expanse#101]
Many people have given feedback on my mod pack, stating that the bio generation speed of this mod is too fast. I hope to set a more reasonable generation speed (such as the issue of generating a large number of drowned corpses and the problem of more juvenile squid than squid)

**Comment by SirSquidly** [comment]
Baby Squid already have a config option to set how many of them spawn, and I believe Drowned Overpopulation is caused by a bug which was solved in 1.1.4.

While I will be adding specific config for spawn rate tweaking later, I recommend the mod _InControl_ if you want an extremely fine-tuned control over Mob Spawning.

**Comment by SirSquidly** [comment]
As the spawning of Baby Squids is just fine and Drowned has been fixed already, I am closing this issue.
