### ISSUE TITLE
Random lime dye furnace recipe

### ISSUE THREAD

**Issue by Michael-Sebero** [SirSquidly/Oceanic-Expanse#103]
![screenshot_20241027-185906](https://github.com/user-attachments/assets/f9036d8a-2305-4dd7-87d8-60b3cf32ace6)

**Comment by SirSquidly** [comment]
Someone else I had spoken with gave more info on this: It occurs when Sea Pickles have been disabled.

This is simply caused because I forgot to add a check if Sea Pickles are registered when adding the smelting recipe:
https://github.com/SirSquidly/Oceanic-Expanse/blob/c95f775409277fe7669eee5188a558b1534ed3e9/src/main/java/com/sirsquidly/oe/init/OERecipes.java#L24

Should be a very easy fix.

**Comment by SirSquidly** [comment]
Fixed in 1.1.5
