### ISSUE TITLE
PVJ (Project Vibrent Journeys) causes most of this mod's mobs to no longer spawn.

### ISSUE THREAD

**Issue by MagmaSlime123** [SirSquidly/Oceanic-Expanse#109]
**Description**
Title. Fish of all kinds, along with Crabs, Clams, Lobsters, and Glow Squids/their babies do not spawn in oceans. Turtles and Baby Squids seem to be fine, however.

**Additional Files**
![2024-12-16_12 47 29](https://github.com/user-attachments/assets/fc08ddaf-3099-49cd-bb49-0dcfa2d22923)
![image](https://github.com/user-attachments/assets/5bff2020-24e3-4b98-9121-7828c87c25a1)
No other mods are loaded, and no crashes or logs appear. This has nothing to do with that.

**Comment by SirSquidly** [comment]
Testing this a bit, I can confirm that it is an issue, although I notice that vanilla squids also are much rarer with PVJ installed.

It will take some time to look into why this is occurring as it isn't obvious checking their repository, I suspect it might be due to the high spawn wights of PVJ mobs?

**Comment by MagmaSlime123** [comment]
I'm not sure. I didn't touch any of its configs.

**Comment by Norfried** [comment]
I solved the problem by completely disabling starfish spawns. I don't know why this happens, but PVJ starfish will out spawn the majority of ocean life no matter what you set their spawn rate to. After I set their spawn rate to 0, all other mobs in the sea started spawning as they normally would. No need to disable the beach stars, they spawn on land in beach biomes, though I haven't seen any since I disabled the regular stars (could be because of other mobs in my modpack that spawn on the shore).

**Comment by Norfried** [comment]
Had I noticed this earlier in the week I would've explained my solution sooner. This is yet another 1.12.2 Project Vibrant Journeys issue, not an issue on Oceanic Expanse's end.

**Comment by MagmaSlime123** [comment]
Well, they won't support 1.12. So unless you fix their spawnrate issues via mixins or whatever, there's not much I can do from my end. Glow Squds are still not spawning though.

You might've made an oopsie too, btw. See #113.

**Comment by SirSquidly** [comment]
Thank you Norfried, investigating I can see that Starfish from PVJ are filling the mob cap. This is an issue on their end, thus nothing for me to deal with.

> Well, they won't support 1.12. So unless you fix their spawnrate issues via mixins or whatever, there's not much I can do from my end.

As Norfried mentioned, PVJ includes a config option which disables Starfish Spawning. Since their spawning causes issues, you can easily turn it off.
