### ISSUE TITLE
Drowned AI crash

### ISSUE THREAD

**Issue by michelegargiulo** [SirSquidly/Oceanic-Expanse#46]
Happens when there is a drowned anywhere nearby a door.

[crash-2023-09-21_19.52.16-server.txt](https://github.com/SirSquidly/Oceanic-Expanse/files/12689912/crash-2023-09-21_19.52.16-server.txt)

**Comment by SirSquidly** [comment]
This is odd, as Drowned should not have the `EntityAIBreakDoor` AI Task, as I have had it disabled even before the mod was released.

I am suspecting this is similar to [issue #19](https://github.com/SirSquidly/Oceanic-Expanse/issues/19), where another mod is forcing the AI onto the drowned because it parents the Zombie class. 

Try disabling some of the mods that might alter Entities to see which it could be, then let me know which one is causing the issue.

**Comment by michelegargiulo** [comment]
Unfortunately, despite my attemps, I was not able to find the culprit mod(s). Probably, more than one of the mods I've installed adds that. From my testing, I can say that it was not:

* RLTweaker
* Roughmobs Revamped
* RandomTweaks

I ended up writing a quick patch to the Drowned AI, a simple line in the `onUpdate()` function that checks if the `EntityAIBreakDoor` is in the entity tasks and removes it. Not ideal, but works. Closing this issue for now.
