### ISSUE TITLE
Incompatibility with SimpleDifficulty

### ISSUE THREAD

**Issue by Noble772** [SirSquidly/Oceanic-Expanse#52]
When SimpleDifficulty is installed, the game will crash when around beaches with Oceanic Expanse installed.

[latest.log](https://github.com/SirSquidly/Oceanic-Expanse/files/13855531/latest.log)

**Comment by SirSquidly** [comment]
I have loaded Oceanic Expanse 1.0.7 and SimpleDifficulty 0.3.9, and have experienced zero crashes near beaches or the ocean.

Your log shows a modpack worth of mods, with barely any mentions of OE (Oceanic Expanse) in it, and zero errors in Oceanic Expanse.

Please load Oceanic Expanse and SimpleDifficulty _only_ to see if that is the issue, because on my end, this is another mod's problem.

**Comment by Noble772** [comment]
Sorry, I should've only loaded SimpleDifficulty and Oceanic Expanse in the first place. Turns out it was caused by my attempt to disable sea oats in the config. For some reason it was generating air blocks with the sandy trait that caused the blocks to render as a purple and black texture in place in sea oats instead of removing them. These air blocks were causing simple difficulty to crash.

**Comment by SirSquidly** [comment]
Wait, that sounds like a real issue! I'm going to open a new issue for that!
