### ISSUE TITLE
OceanicExpanse 1.1.0 with Buildcraft compatibility issue

### ISSUE THREAD

**Issue by Robolightning** [SirSquidly/Oceanic-Expanse#67]
Full logs:
[2024-04-25-2.log.gz](https://github.com/SirSquidly/Oceanic-Expanse/files/15115236/2024-04-25-2.log.gz)
[crash-2024-04-25_20.13.22-client.txt](https://github.com/SirSquidly/Oceanic-Expanse/files/15115047/crash-2024-04-25_20.13.22-client.txt)

**Comment by SirSquidly** [comment]
So, this is a real bad issue.

Basically, I removed Tall Seagreass and Mid-Kelp in 1.1.0, as they were technical blocks that just created issues.

I did this by making them just _load_ as a different block, to replace themselves instantly. This is because Forge's built-in Replace doesn't support replacing removed blocks with _existing_ blocks

Best solution might to just make 1.1.0 flat incompatible with ANY worlds made in previous versions.

**Comment by SirSquidly** [comment]
Re-opened, until the update is released. Sorry, that was an accident!

**Comment by Robolightning** [comment]
> So, this is a real bad issue.
> 
> Basically, I removed Tall Seagreass and Mid-Kelp in 1.1.0, as they were technical blocks that just created issues.
> 
> I did this by making them just _load_ as a different block, to replace themselves instantly. This is because Forge's built-in Replace doesn't support replacing removed blocks with _existing_ blocks
> 
> Best solution might to just make 1.1.0 flat incompatible with ANY worlds made in previous versions.

The problem occurs when startering the game, not when entering the world

**Comment by SirSquidly** [comment]
> The problem occurs when startering the game, not when entering the world

... Yes, I am perfectly aware of that. I said nothing contradicting that.

**Comment by SirSquidly** [comment]
Fixed in 1.1.1
