### ISSUE TITLE
Lobster crash on server

### ISSUE THREAD

**Issue by TheForgottenKing** [SirSquidly/Oceanic-Expanse#97]
This is an occasional issue that I've encountered on 1.1.3. Lobsters cause a TickingEntity crash. I can't disable the other mods since that will break the world but this seems to be only OceanicExpanse causing the crash. The only fix is removing OceanicExpanse. I tried deleting the affected lobster but then the server crashes on startup with a different lobster. Not sure what triggers it.

Crash report is attached.

[crash-2024-08-11_20.08.39-server.txt](https://github.com/user-attachments/files/16577182/crash-2024-08-11_20.08.39-server.txt)

**Comment by SirSquidly** [comment]
Big Yikes on that, testing on my own server shows this is an extreme issue! This is caused by [Line 310](https://github.com/SirSquidly/Oceanic-Expanse/blob/57b332db7f998f88a324b3338bca2dd54671c157/src/main/java/com/sirsquidly/oe/entity/EntityLobster.java#L310), specifically the `.getAge()` check, which I was not aware is ClientSide Only in `EntityItem`!

https://github.com/SirSquidly/Oceanic-Expanse/blob/57b332db7f998f88a324b3338bca2dd54671c157/src/main/java/com/sirsquidly/oe/entity/EntityLobster.java#L310

I have swapped this to a simple `ticksExisted` check, which resolved the issue in testing. Expect the bugfix update to be released extremely soon, likely tomorrow.

**Comment by SirSquidly** [comment]
Fixed in 1.1.4
